// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1645560855);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1645560975);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1645560495);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1645560615);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1645560735);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1645240274);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1645561095);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 450145);
user_pref("browser.cache.disk.capacity", 819200);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1645231679);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8156a030-dce1-45f5-8fe7-2cbde0f3068e}");
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1645264308995");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1645266105995");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1645253283771");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1645274883771");
user_pref("browser.search.region", "ID");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200403171148");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1645560466");
user_pref("browser.slowStartup.averageTime", 1204);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200403171148");
user_pref("browser.startup.homepage_override.mstone", "68.7.0");
user_pref("browser.startup.lastColdStartupCheck", 1645560465);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.7.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1645560856);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20200403171148");
user_pref("extensions.lastAppVersion", "68.7.0");
user_pref("extensions.lastPlatformVersion", "68.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"29252ea7-afcc-4209-b217-47ca854ee9d4\",\"fxmonitor@mozilla.org\":\"32826060-1fea-4a91-b7af-2ed409506737\",\"screenshots@mozilla.org\":\"e6d5c758-6707-48af-af7c-b3ff98a8bf72\",\"webcompat-reporter@mozilla.org\":\"84331d7e-3a03-47ec-840f-282a34320ef5\",\"webcompat@mozilla.org\":\"926da868-592c-439a-852b-bbea0e0ac033\",\"default-theme@mozilla.org\":\"7a0a52a2-0d09-4a45-a310-3f6254dd6389\",\"google@search.mozilla.org\":\"dea81d6a-e94c-45af-a8af-01c81a30ce15\",\"amazondotcom@search.mozilla.org\":\"4a825d87-54be-4bb7-b754-3bb59eaf223b\",\"bing@search.mozilla.org\":\"84e16a06-d639-4f7e-bb9d-322646eae8b0\",\"ddg@search.mozilla.org\":\"cc0d1925-4f69-4602-820c-f6f17c7a3e41\",\"ebay@search.mozilla.org\":\"99151d8b-06c0-4431-89a4-0c1e8a4380e8\",\"twitter@search.mozilla.org\":\"43cf0806-f9cf-4149-b80d-92a113325b7b\",\"wikipedia@search.mozilla.org\":\"de96aa7d-5880-47c7-9e08-72722efc4d1e\"}");
user_pref("idle.lastDailyNotification", 1645243112);
user_pref("media.benchmark.vp9.fps", 251);
user_pref("media.benchmark.vp9.versioncheck", 5);
user_pref("media.gmp-manager.buildID", "20200403171148");
user_pref("media.gmp-manager.lastCheck", 1645560681);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{04a360bc-189e-414d-9a21-4b1bab45d685}");
user_pref("places.database.lastMaintenance", 1645243112);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "7100db5b-6369-4713-93f5-4ec69c244e21");
user_pref("security.sandbox.plugin.tempDirSuffix", "7162a828-ed11-43e3-bfc6-79df9dd42bd8");
user_pref("services.settings.clock_skew_seconds", 25202);
user_pref("services.settings.last_etag", "\"1645533483777\"");
user_pref("services.settings.last_update_seconds", 1645535533);
user_pref("services.settings.main.cfr.last_check", 1645535533);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1645535533);
user_pref("services.settings.main.hijack-blocklists.last_check", 1645535533);
user_pref("services.settings.main.language-dictionaries.last_check", 1645535533);
user_pref("services.settings.main.sites-classification.last_check", 1645535533);
user_pref("services.settings.main.tippytop.last_check", 1645535533);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1645535533);
user_pref("services.settings.security.onecrl.checked", 1645535533);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1645243112);
user_pref("toolkit.startup.last_success", 1645560464);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20200403171148");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
